### ISSUE TITLE
Lab instead of RGB?

### ISSUE THREAD

**Issue by Santinell** [XadillaX/thmclrx#3]
What do you think about change for better search color space from RGB to Lab or LCH?
I am not profi, but in CIE76 (color diff. algorithm) using euclidian distance in Lab color space.
In CIE94 used LCH color space.

**Comment by XadillaX** [comment]
Sry, I don't know those algorithms.

I will add `learn CIE76` into my TODO list and write a CIE76 version of thmclrx.

But in `octree algorithm`, the calculation is using RGB color space.

**Comment by Santinell** [comment]
As I know octree algorithm can be used for searching nearest neighbor in 3-dimensional space.
Lab is also has 3 dimensions

**Comment by XadillaX** [comment]
@Santinell But in reducing colors, `octree algorithm` using `R`, `G` and `B` these three dimensions.

**Comment by Santinell** [comment]
http://en.wikipedia.org/wiki/Color_quantization#Algorithms
"The three color channels are usually red, green, and blue, but another popular choice is the Lab color space, in which Euclidean distance is more consistent with perceptual difference."

**Comment by XadillaX** [comment]
@Santinell Thx very much. I will read that for further. And would you please to improve this package together?
