### ISSUE TITLE
Hit stdint.h not find in node 0.12.2

### ISSUE THREAD

**Issue by chinajuanbob** [XadillaX/thmclrx#4]
node_modules\thmclrx\src\third-party\xmempool\xmempool.h(23): fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory

Any clue for this? Thanks!

**Comment by XadillaX** [comment]
Which system did you use? Linux, MacOS or Windows?

**Comment by chinajuanbob** [comment]
Windows 7

**Comment by XadillaX** [comment]
@chinajuanbob have you ever installed Visual Studio?

**Comment by chinajuanbob** [comment]
I have VS 2012, it is weird that stdint.h is in the PATH.
Is it a common issue or just with my environment?

**Comment by XadillaX** [comment]
@chinajuanbob I just fixed a bug under windows. But it seems not the bug of `stdint.h`. You may search on the Internet about `stdint.h` in Visutal Studio.

**Comment by XadillaX** [comment]
Have you ever solved the problem?

**Comment by chinajuanbob** [comment]
No, unfortunately, there are still errors with your latest change.

427 info thmclrx@0.3.1 Failed to exec install script
429 verbose stack Error: thmclrx@0.3.1 install: `node-gyp rebuild`
429 verbose stack Exit status 1
429 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
429 verbose stack     at EventEmitter.emit (events.js:110:17)
429 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
429 verbose stack     at ChildProcess.emit (events.js:110:17)
429 verbose stack     at maybeClose (child_process.js:1015:16)
429 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

434 error node v0.12.2
435 error npm  v2.7.4
436 error code ELIFECYCLE
437 error thmclrx@0.3.1 install: `node-gyp rebuild`
437 error Exit status 1
438 error Failed at the thmclrx@0.3.1 install script 'node-gyp rebuild'.
438 error This is most likely a problem with the thmclrx package,
438 error not with npm itself.
438 error Tell the author that this fails on your system:
438 error     node-gyp rebuild

**Comment by chinajuanbob** [comment]
Solve it by set 'npm config set msvs_version 2012 --global' and compile with latest change manually.

reference: http://stackoverflow.com/questions/21562038/node-gyp-build-error-windows-x64

**Comment by XadillaX** [comment]
How about using `0.3.2` this new version?

**Comment by chinajuanbob** [comment]
Yes, I used this new version.
I think it is ok to close this one, Thanks a lot!
