### ISSUE TITLE
Could input be a Stream or Buffer instead of file path?

### ISSUE THREAD

**Issue by chinajuanbob** [XadillaX/thmclrx#5]
I find huge memory usage when handle with big photo, like 3000 * 2000, so thinking of resize or reduce color of the image on fly first, then use thmclrx.
If not, any plan for this? Thanks a lot!

**Comment by XadillaX** [comment]
In Huaban, we resized the picture in the business logic layer.

If the input is stream, the algorithm may a bit hard to impl.

**Comment by chinajuanbob** [comment]
Got it, I suggest add a note for the memory usage with image size, kind of a limitation from my perspective.
Thanks!
