### ISSUE TITLE
linux 安装 thmclrx的时候报错

### ISSUE THREAD

**Issue by FZliweiliang** [XadillaX/thmclrx#8]
`In file included from ../deps/byakuren/const/palette.c:55:0:
../deps/byakuren/const/palette.h:62:1: warning: ‘extern’ is not at beginning of declaration [-Wold-style-declaration]
 const extern bkr_palette_array _default_palette;
 ^
  CC(target) Release/obj.target/byakuren/deps/byakuren/lib/mindiff.o
In file included from ../deps/byakuren/lib/mindiff.c:56:0:
../deps/byakuren/lib/../const/palette.h:62:1: warning: ‘extern’ is not at beginning of declaration [-Wold-style-declaration]
 const extern bkr_palette_array _default_palette;
 ^
../deps/byakuren/lib/mindiff.c: In function ‘_bkr_find_mindiff’:
../deps/byakuren/lib/mindiff.c:75:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(uint32_t i = 0; i < palette_count; i++)
     ^
../deps/byakuren/lib/mindiff.c:75:5: note: use option -std=c99 or -std=gnu99 to compile your code
../deps/byakuren/lib/mindiff.c: In function ‘_bkr_mindiff_calc’:
../deps/byakuren/lib/mindiff.c:94:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(uint32_t i = 0; i < pixel_count; i++)
     ^
../deps/byakuren/lib/mindiff.c:105:18: error: redefinition of ‘i’
     for(uint32_t i = 0; i < colored_count; i++)
                  ^
../deps/byakuren/lib/mindiff.c:94:18: note: previous definition of ‘i’ was here
     for(uint32_t i = 0; i < pixel_count; i++)
                  ^
../deps/byakuren/lib/mindiff.c:105:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(uint32_t i = 0; i < colored_count; i++)
     ^
../deps/byakuren/lib/mindiff.c:112:18: error: redefinition of ‘i’
     for(uint32_t i = 0; i < grayed_count; i++)
                  ^
../deps/byakuren/lib/mindiff.c:105:18: note: previous definition of ‘i’ was here
     for(uint32_t i = 0; i < colored_count; i++)
                  ^
../deps/byakuren/lib/mindiff.c:112:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(uint32_t i = 0; i < grayed_count; i++)
     ^
../deps/byakuren/lib/mindiff.c: In function ‘_bkr_generate_colored_and_gray_pelette’:
../deps/byakuren/lib/mindiff.c:152:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for(uint32_t i = 0; i < palette->count; i++)
         ^
../deps/byakuren/lib/mindiff.c:165:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for(uint32_t i = 0; i < palette->count; i++)
`

**Comment by XadillaX** [comment]
v2.0.1 应该已经解决了。
